apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-rollout-bluegreen
  labels:
    app: my-app
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    blueGreen:
      activeService: my-app-service-active
      previewService: my-app-service-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: my-app-rollout-bluegreen
  template:
    metadata:
      labels:
        app: my-app-rollout-bluegreen
    spec:
      containers:
        - name: my-app-rollout-bluegreen
          image: 061165606031.dkr.ecr.ap-northeast-2.amazonaws.com/my-app:e258059
          ports:
            - containerPort: 4000
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service-active
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:061165606031:certificate/2bd72fa1-e471-49c6-ad45-1ca6738bbbf1
    external-dns.alpha.kubernetes.io/hostname: cloudplayer.link
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  selector:
    app: my-app-rollout-bluegreen
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service-preview
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:061165606031:certificate/2bd72fa1-e471-49c6-ad45-1ca6738bbbf1
    external-dns.alpha.kubernetes.io/hostname: cloudplayer.link
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
  selector:
    app: my-app-rollout-bluegreen
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 4000
